baseURL = "https://4ad.app/"
locale = "en_GB"
title = "4AD: Companion"
disableKinds = ["taxonomy", "term"]

[params]
description = "An offline iPhone and iPad companion for tracking Four Against Darkness parties, dungeon maps, sessions, encounters, and dice rolls."

[caches]
[caches.images]
dir = ':cacheDir/images'
